name: NoneBot Auto Changelog
author: yanyongyu <yyy@nonebot.dev>
description: nonebot auto changelog
inputs:
  changelog_file:
    description: The changelog file to update
    required: false
  latest_changes_position:
    description: The latest changes position in the changelog file
    required: false
  latest_changes_title:
    description: The latest changes title in the changelog file
    required: false
  replace_regex:
    description: Replace latest changes body pattern
    required: false
  changelog_body:
    description: The changelog body
    required: false
  archive_regex:
    description: Archive latest changes pattern
    required: false
  archive_title:
    description: Archive latest changes title
    required: false
  commit_and_push:
    description: Whether to commit and push changes
    required: false

runs:
  using: docker
  image: Dockerfile
branding:
  icon: box
  color: orange
