name: Changelog

on:
  pull_request_target:
    branches:
      - master
    types:
      - closed

jobs:
  update_changelog:
    if: github.event_name == 'pull_request_target'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: release-drafter/release-drafter@v5
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: nonebot/auto-changelog@master
        with:
          changelog_body: ${{ steps.release-drafter.outputs.body }}
